#!/usr/bin/env bash
# UI_HARNESS.sh — VIVE Statement Reconciliation
# Generated by PBVI Phase 8 — UI Harness Assembly (PBVI-011)
# Trigger: Phase 8 completion and on-demand only
# Do not run at session end — Playwright requires browser runtime

set -e

echo "=== UI Harness — VIVE Statement Reconciliation ==="
echo "Running Playwright test suite from ui_tests/"
echo ""

npx playwright test ui_tests/ --reporter=list

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo ""
  echo "=== UI HARNESS: PASS ==="
else
  echo ""
  echo "=== UI HARNESS: FAIL — see output above ==="
fi

exit $EXIT_CODE
